# Generated by Django 3.0.8 on 2020-07-13 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellomaster', '0003_comment_postimage_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='title',
            new_name='category',
        ),
    ]
