# Generated by Django 3.0.8 on 2020-07-14 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sellomaster', '0006_product_dd'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(default='', max_length=64, verbose_name='country')),
            ],
            options={
                'verbose_name_plural': 'Категорий',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(default='', max_length=64, verbose_name='currency')),
            ],
            options={
                'verbose_name_plural': 'Категорий',
            },
        ),
        migrations.RemoveField(
            model_name='product',
            name='dd',
        ),
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sellomaster.Currency'),
        ),
        migrations.AlterField(
            model_name='product',
            name='country',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='sellomaster.Country'),
        ),
    ]
