# Generated by Django 3.0.8 on 2020-07-14 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellomaster', '0007_auto_20200714_1533'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterModelOptions(
            name='currency',
            options={'verbose_name_plural': 'Валюты'},
        ),
    ]
