# Generated by Django 3.0.8 on 2020-07-14 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellomaster', '0008_auto_20200714_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='contact',
        ),
    ]
