# Generated by Django 3.0.8 on 2020-07-14 15:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellomaster', '0010_auto_20200714_1543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_pub',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='product',
            name='date_publeshed',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
