# Generated by Django 3.0.8 on 2020-07-16 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellomaster', '0012_auto_20200714_1558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='date_publeshed',
            field=models.DateField(auto_now_add=True),
        ),
    ]
