# Generated by Django 3.0.8 on 2020-07-16 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellomaster', '0017_mailus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_pub',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
