# Generated by Django 3.0.8 on 2020-07-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellomaster', '0018_auto_20200716_1311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category'], 'verbose_name': 'Категория', 'verbose_name_plural': 'Категорий'},
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(db_index=True, default='', max_length=64, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='country',
            name='country',
            field=models.CharField(default='', max_length=64, verbose_name='Старана'),
        ),
        migrations.AlterField(
            model_name='currency',
            name='currency',
            field=models.CharField(default='', max_length=64, verbose_name='Валюта'),
        ),
    ]
